version: 2.1

executors:
  ask-executor:
    docker:
      - image: martindsouza/amazon-ask-cli

jobs:
  checkout:
    executor: ask-executor
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
  build:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/node/
      - run: ls -la
      - run: cd lambda/custom && npm install


workflows:
    skill-pipeline:
      jobs:
        - checkout
        - build:
            requires:
              - checkout