version: 2.1

executors:
  ask-executor:
    docker:
      - image: martindsouza/amazon-ask-cli

jobs:
  checkout:
    executor: ask-executor
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
  build:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/node/
      - run: ls -la
      - run: cd lambda/custom && npm install
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
  test:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/node/
      - run: ls -la
      - run: cd lambda/custom && npm run test
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
  deploy:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/node/
      - run: rm -rf /home/node/.ask
      - run: rm -rf /home/node/.aws
      - run: ls -la
      - run: ask deploy
      - run: cd lambda/custom && npm clean
      - store_artifacts:
          path: ./


workflows:
    skill-pipeline:
      jobs:
        - checkout
        - build:
            requires:
              - checkout
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test