version: 2.1

executors:
  ask-executor:
    docker:
      - image: xavidop/alexa-ask-aws-cli:1.0

jobs:
  checkout:
    executor: ask-executor
    steps:
      - checkout
      - run: pwd
      - persist_to_workspace:
          root: /home/root/
          paths:
            - project
  build:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/root/
      - run: ls -la
      - run: cd lambda/custom && npm install
      - persist_to_workspace:
          root: /home/root/
          paths:
            - project
  test:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/root/
      - run: ls -la
      - run: cd lambda/custom && npm run test
      - persist_to_workspace:
          root: /home/root/
          paths:
            - project
  deploy:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/root/
      - run: ls -la
      - run: ask deploy --debug
      - persist_to_workspace:
          root: /home/root/
          paths:
            - project
  store-artifacts:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/root/
      - run: ls -la
      - run: rm -rf lambda/custom/node_modules
      - store_artifacts:
          path: ./
workflows:
    skill-pipeline:
      jobs:
        - checkout
        - build:
            requires:
              - checkout
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test
        - store-artifacts:
            requires:
              - deploy