version: 2.1

executors:
  ask-executor:
    docker:
      - image: martindsouza/amazon-ask-cli

jobs:
  checkout:
    executor: ask-executor
    steps:
      - checkout
  build:
    executor: ask-executor
    steps:
      - run: pwd
      - run: ls -la


workflows:
    init:
      jobs:
        - checkout
        - build:
            requires:
              - checkout